name: Deploy to Microsoft Storage Account

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Zip artifcat for deployement job # This is needed because I use a different job for deployment
        run: zip dist.zip ./dist/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: addin-build
          path: dist.zip
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: addin-build

      - name: Unzip artifact for deployment
        run: |
          unzip dist.zip
          ls
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name sadspoonstorage  --auth-mode key -d '$web' -s ./dist

      # Azure logout
      - name: Logout from Azure
        run: |
              az logout
        if: always()
